# Generated by Django 5.0 on 2024-04-24 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_oder_order_date_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custommer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custommer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custommer',
            new_name='customer',
        ),
    ]
